### ISSUE TITLE
CSRF detected with Omniauth and Sinatra

### ISSUE THREAD

**Issue by regdog** [NeverMin/omniauth-wechat-oauth2#1]
Firstly thank you for the great gem! But I have met this CSRF detected issue with my sinatra program! How to solve it?
I am using:
omniauth (1.2.1)
omniauth-oauth2 (1.1.2)
omniauth-wechat-oauth2 (0.1.0)

``` ruby
# app.rb
require 'sinatra'
require 'sinatra/json'
require 'omniauth-wechat-oauth2'

WECHAT_API_KEY = 'xxxxxxxxxxxxxxxxxxxx'
WECHAT_APP_SECRET = 'xxxxxxxxxxxxxxxxxxxx'

enable :sessions

use OmniAuth::Builder do
  provider :wechat, WECHAT_API_KEY, WECHAT_APP_SECRET
end

get '/' do
  <<-HTML
  <a href='/auth/wechat'>微信登录</a>
  HTML
end

post '/auth/wechat/callback' do
  auth = request.env['omniauth.auth']
  auth.inspect
end

get '/auth/failure' do
  redirect '/'
end
```

---

I also run another sinatra program for testing omniauth-github. It works! So could it be en error of this gem? 

thanks!
regdog

**Comment by mouse-lin** [comment]
Upstairs is right.

**Comment by apetitdev** [comment]
"ignore CSRF detection on callback phase" That sounds really not secure to do that, how about CSRF attacks?
