### ISSUE TITLE
Unable to initiate the authorization

### ISSUE THREAD

**Issue by thirtysixetcetera** [NeverMin/omniauth-wechat-oauth2#3]
I created a simple rails app with just the following 2 gems installed.

gem 'devise'
gem "omniauth-wechat-oauth2"

I put the app_id and secret as usual in the config/initializers/devise.rb and use the devise sign in page to logon to WeChat. 

Once I login to WeChat, I got the "Sorry Page" saying "Oops! Something went wrong :(". I looked at the log/development.log. Only "Started GET "/users/auth/wechat" was printed. 

Do you have any idea what is going on?

**Comment by zlx** [comment]
@Fatman13 你好，我也碰到了同样的问题，请问你是如何解决的？在开发环境下如何配置这个域名？

**Comment by cgg5207** [comment]
@zlx @Fatman13 
测试环境，那就用80端口，把本端映射到外网的域名上。
1. http://dlj.bz/m037
2. https://ngrok.com/

**Comment by gangcai** [comment]
同样的问题，用的是微信测试号

**Comment by NeverMin** [comment]
由于此问题时间有点久，如果还有遇到此问题的话，欢迎新开 issue.
