### ISSUE TITLE
自建gitlab，想整合企业微信OAuth登录，不知道如何弄？

### ISSUE THREAD

**Issue by softboy99** [NeverMin/omniauth-wechat-oauth2#37]
这个库可以做到吗？怎么弄？请指教，多谢！

**Comment by Eric-Guo** [comment]
理论上包含这个gem，然后直接在gitlab.yml里面的`omniauth:`加一条配置即可，这个需求和添加2.0的支持肯定没关系，因为gitlab现在的omniauth还在1.9.1。

**Comment by softboy99** [comment]
gitlab的版本更新很快，不同版本有很大不同，安装了最新的14.7.2，不知道在哪个路径的哪个文件中包含这个“gem”,在此之前尝试用它自带的oauth2_generic，失败，因为usrinfo_url 返回的信息中缺少邮箱，报422错误

**Comment by Eric-Guo** [comment]
那你改一下usrinfo_url返回，添加一个邮箱就好了啊，这个问题起码比整合企业微信容易多了，或者你可以看一下gitlab jh版本的dingding talk怎么做的，具体这块我也不熟。

**Comment by softboy99** [comment]
userinfo_url是企业微信的api,我们改不了啊，钉钉的有返回email

**Comment by Eric-Guo** [comment]
gitlab 源码可以改的，另外官方的意思是欢迎MR啊。。

**Comment by softboy99** [comment]
那必须源码安装才可以
