### ISSUE TITLE
Hi, are you sure it's "mp.weixin.qq.com", not "open.weixin.qq.com"?

### ISSUE THREAD

**Issue by zzz6519003** [NeverMin/omniauth-wechat-oauth2#7]
Thx for your work!

**Comment by Gataniel** [comment]
Any update on this? mp.weixin.qq.com requires lots of business info I don't have. Simply want to implement user loging in via WeChat. open.weixin.qq.com requires Chinese mobile phone number I don't have

**Comment by mouse-lin** [comment]
@zzz6519003 http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html
It's "open.weixin.qq.com"

**Comment by trammel** [comment]
open.weixin.qq.com requires it too. Chinese phone number, address and ID card required.

![image](https://cloud.githubusercontent.com/assets/97644/18907572/815e5e36-85af-11e6-8905-2b9fafae3df5.png)

**Comment by sahilpurav** [comment]
open.weixin.qq.com doesn't work on in-app browser. We have to use mp.weixin.qq.com.

I wanted to know whag is the exact difference between this two URLs

**Comment by NeverMin** [comment]
Sorry, this is Tencent issue.

ref: https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839
